### ISSUE TITLE
Suggestion: Add last release/commit

### ISSUE THREAD

**Issue by williamhatcher** [apacheli/discord-api-libs#52]
Great job creating this resource. 

Is it possible to include the last release date, or if that doesn't exist, the last commit date?

**Comment by apacheli** [comment]
Yes, I could add something like this. I'll see what I can do. How do you want this data to be represented? My current idea is:

```jsonc
{
  "latest_version": "3.0.0", // or a release hash
  "latest_version_date": 1678400977 // ISO timestamp
}
```

**Comment by williamhatcher** [comment]
Sounds good, though I think adding a `latest_commit_date` might be helpful. Don't know how often your script gets ran though.

**Comment by apacheli** [comment]
Only took a year, but I have an open PR to fetch the the latest commit date for each library: https://github.com/apacheli/discord-api-libs/tree/rework-json

Inside `data/libraries.json`, you can access the `pushed_at` property to obtain the latest commit date. It is in the format of an integer timestamp based on milliseconds.

I am still making a few adjustments to it though before I merge.

**Comment by apacheli** [comment]
The branch is merged and should be polling once a day at 00:00 (UTC-0).
