### ISSUE TITLE
Remove discord.io (JavaScript)

### ISSUE THREAD

**Issue by vegeta897** [apacheli/discord-api-libs#60]
Discord.io has not been updated since 2018, and the repo was archived in 2020. The sole creator/maintainer declared it dead for years and has no intention of returning to it.

**Comment by apacheli** [comment]
discord.io is currently marked as archived in [`libraries.json`](https://github.com/apacheli/discord-api-libs/blob/master/libraries.json#L411-L425). Unless the maintainer requests directly the removal of discord.io from this list, it will remain here for archival purposes.
