### ISSUE TITLE
Remove DiscordPHP-Slash from the list of PHP libraries.

### ISSUE THREAD

**Issue by valzargaming** [apacheli/discord-api-libs#62]
https://github.com/apacheli/discord-api-libs/blob/3af94b0aefc5e31ea9e0b7aec7eda275b6292b07/README.md?plain=1#L134

The library is archived and the functionality it provided is now built directly into the DiscordPHP library.

**Comment by apacheli** [comment]
These libraries were already marked as archived, but it appears that I have not correctly labeled them in Markdown. Fixed in #63.
